### ISSUE TITLE
New queryables to pyCSW opensearch

### ISSUE THREAD

**Issue by ferrighi** [metno/S-ENDA-documentation#237]

**Comment by epifanio** [comment]
We managed to have a better knowledge of the pycsw src code in order to implement this - however, it was not required to accomplish most of the prefixed targets.

A good overview of the problem and an understanding of the src code changes required is given by the following  PR:  https://github.com/geopython/pycsw/pull/642  in particular this commit:   https://github.com/geopython/pycsw/pull/642/commits/c82cb6e0e782a2601a86f58a9e33f2080382b46c

depending on what we need to do with the new field, and how to access it -- it will require a series of changes along with the whole CSW src code - see the PR involves 58 file-changes -  most of the files changes are needed to update the tests routine and the documentation.

The main src code files involved are:
* admin.py  which is where the pycsw records table is created - so this will be the starting point
* config.py 
* csw2/3.py (expose the new fields into the csw model)
* apiso.py - to expose them in the ISO profile output

 for internal use and development purposes - the modification required is not that hard - However, if we want those changes merged in csw ... or exposed to OpenSearch - that will be doable but a bit harder and time-consuming.

**Comment by ferrighi** [comment]
@epifanio can we close this now?

**Comment by epifanio** [comment]
Yes please. We used the notes above to add new fields into the pycsw db backend and expose them to the dif profile. However we are still testing the system stability on a development/testing branch.
