### ISSUE TITLE
Add platform instruments to Lara's instruments list

### ISSUE THREAD

**Issue by TAlonglong** [metno/S-ENDA-documentation#243]
That list will be added to the MMD repo when ready.

**Comment by TAlonglong** [comment]
https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#instruments

Looks ok to me

**Comment by ferrighi** [comment]
In the list of instruments we have AVHRR and AVHRR/2 which are hosted on NOAA-6,8,10 (and TIROS-N) and NOAA-7,9,11,12,13,14. These platforms are not currently part of the platform list. 
Should we remove these instruments or add these platforms? @TAlonglong

**Comment by TAlonglong** [comment]
Hm I see.

We currently don't have any AVHRR nor AVHRR/2 dataset available.

But we have some data on tapes that might have at least AVHRR/2. I'm not sure it these data ever will find the way out of the tapes. But Øystein mentioned he would like to see that.

But the point is: If we add, say NOAA-6, will it confuse the user to believe we have NOAA-6 data? If so we should not list it.

So I suggest to remove AVHRR and AVHRR/2, and add this with the corresponding platform names later if needed.

**Comment by ferrighi** [comment]
I don't think it's a problem at all adding NOAA-6. The list is not about what we have, but what we support as entries (same for licenses for example, we don't use most of them). The issue is that if we support the instrument we should support also the related platform. But if we don't need them for now we can just remove them and open an issue later on to add a new platform and related instruments.
